SET check_function_bodies = false;
CREATE SCHEMA schema1;
CREATE SCHEMA schema2;
CREATE TABLE public.test_cast_1 (
    id integer NOT NULL,
    name text NOT NULL,
    net_worth bigint NOT NULL
);
CREATE FUNCTION public.cast_net_value(test_row public.test_cast_1) RETURNS text
    LANGUAGE sql STABLE
    AS $$
  SELECT CAST(test_row.net_worth as TEXT)
$$;
CREATE TABLE public.api_test (
    id integer NOT NULL,
    locationkey text,
    locationname text
);
ALTER TABLE public.api_test ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_test_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.ashok_test (
    id integer NOT NULL,
    "locationKey" text NOT NULL,
    "locationName" text NOT NULL
);
COMMENT ON TABLE public.ashok_test IS 'Test Table';
CREATE TABLE public.ashok_test_2 (
    id integer NOT NULL,
    "locationKey" text NOT NULL,
    "locationName" text NOT NULL
);
COMMENT ON TABLE public.ashok_test_2 IS 'Test Table';
CREATE SEQUENCE public.ashok_test_2_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.ashok_test_2_id_seq OWNED BY public.ashok_test_2.id;
CREATE SEQUENCE public.ashok_test_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.ashok_test_id_seq OWNED BY public.ashok_test.id;
CREATE TABLE public.message (
    id integer NOT NULL,
    content text NOT NULL,
    author text NOT NULL
);
CREATE SEQUENCE public.message_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.message_id_seq OWNED BY public.message.id;
CREATE TABLE public.orders (
    id integer NOT NULL,
    person_id integer NOT NULL,
    purchased_at timestamp with time zone
);
CREATE SEQUENCE public.orders_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.orders_id_seq OWNED BY public.orders.id;
CREATE TABLE public.person (
    id integer NOT NULL,
    name text NOT NULL
);
CREATE SEQUENCE public.person_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.person_id_seq OWNED BY public.person.id;
CREATE SEQUENCE public.test_cast_1_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.test_cast_1_id_seq OWNED BY public.test_cast_1.id;
CREATE TABLE public.users (
    id integer NOT NULL,
    account_admin boolean NOT NULL,
    first_name text NOT NULL,
    last_name text NOT NULL,
    completed_onboarding boolean NOT NULL
);
COMMENT ON TABLE public.users IS 'GH Discussion 9071';
CREATE SEQUENCE public.users_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;
CREATE TABLE schema1.schema1_table_a (
    id integer NOT NULL,
    name text NOT NULL
);
CREATE SEQUENCE schema1.schema1_table_a_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE schema1.schema1_table_a_id_seq OWNED BY schema1.schema1_table_a.id;
CREATE TABLE schema1.schema1_table_b (
    id integer NOT NULL,
    name text NOT NULL
);
CREATE SEQUENCE schema1.schema1_table_b_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE schema1.schema1_table_b_id_seq OWNED BY schema1.schema1_table_b.id;
CREATE TABLE schema2.schema2_table_a (
    id integer NOT NULL,
    name text NOT NULL
);
CREATE SEQUENCE schema2.schema2_table_a_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE schema2.schema2_table_a_id_seq OWNED BY schema2.schema2_table_a.id;
CREATE TABLE schema2.schema2_table_b (
    id integer NOT NULL,
    name text NOT NULL
);
CREATE SEQUENCE schema2.schema2_table_b_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE schema2.schema2_table_b_id_seq OWNED BY schema2.schema2_table_b.id;
ALTER TABLE ONLY public.ashok_test ALTER COLUMN id SET DEFAULT nextval('public.ashok_test_id_seq'::regclass);
ALTER TABLE ONLY public.ashok_test_2 ALTER COLUMN id SET DEFAULT nextval('public.ashok_test_2_id_seq'::regclass);
ALTER TABLE ONLY public.message ALTER COLUMN id SET DEFAULT nextval('public.message_id_seq'::regclass);
ALTER TABLE ONLY public.orders ALTER COLUMN id SET DEFAULT nextval('public.orders_id_seq'::regclass);
ALTER TABLE ONLY public.person ALTER COLUMN id SET DEFAULT nextval('public.person_id_seq'::regclass);
ALTER TABLE ONLY public.test_cast_1 ALTER COLUMN id SET DEFAULT nextval('public.test_cast_1_id_seq'::regclass);
ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);
ALTER TABLE ONLY schema1.schema1_table_a ALTER COLUMN id SET DEFAULT nextval('schema1.schema1_table_a_id_seq'::regclass);
ALTER TABLE ONLY schema1.schema1_table_b ALTER COLUMN id SET DEFAULT nextval('schema1.schema1_table_b_id_seq'::regclass);
ALTER TABLE ONLY schema2.schema2_table_a ALTER COLUMN id SET DEFAULT nextval('schema2.schema2_table_a_id_seq'::regclass);
ALTER TABLE ONLY schema2.schema2_table_b ALTER COLUMN id SET DEFAULT nextval('schema2.schema2_table_b_id_seq'::regclass);
ALTER TABLE ONLY public.api_test
    ADD CONSTRAINT api_test_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.ashok_test_2
    ADD CONSTRAINT ashok_test_2_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.ashok_test
    ADD CONSTRAINT ashok_test_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.message
    ADD CONSTRAINT message_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.person
    ADD CONSTRAINT person_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.test_cast_1
    ADD CONSTRAINT test_cast_1_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);
ALTER TABLE ONLY schema1.schema1_table_a
    ADD CONSTRAINT schema1_table_a_pkey PRIMARY KEY (id);
ALTER TABLE ONLY schema1.schema1_table_b
    ADD CONSTRAINT schema1_table_b_pkey PRIMARY KEY (id);
ALTER TABLE ONLY schema2.schema2_table_a
    ADD CONSTRAINT schema2_table_a_pkey PRIMARY KEY (id);
ALTER TABLE ONLY schema2.schema2_table_b
    ADD CONSTRAINT schema2_table_b_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_person_id_fkey FOREIGN KEY (person_id) REFERENCES public.person(id) ON UPDATE RESTRICT ON DELETE RESTRICT;
